file_path {
	workdir = "/home/isou/lncRNA/LLPS/DLM/LLPS_DLM"
	all_data_feat = ${file_path.workdir}/all_data/all_data_feats.txt
	all_data_interaction = ${file_path.workdir}/all_data/all_total_interactions_seq_list.txt
	all_data_label = ${file_path.workdir}/all_data/all_data_LLPS_label.txt
	all_data_graphsage_model = ${file_path.workdir}/Pre_training_Graph_neural_network/result/all_data__WALK_LEN1_N_WALK_LEN5_bz128/weight/Pretrain_GraphSage_best_epoch.pth
	RPI7317_feat = ${file_path.workdir}/RPI7317_Pretrain_graphsage_dataset/RPI7317_feats.txt
	RPI7317_interaction = ${file_path.workdir}/RPI7317_Pretrain_graphsage_dataset/RPI7317_total_interactions_seq_list.txt
}

setting {
	num_layers = 2
	hidden_emb_size = 100
}
